#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Take_Note.Resource", IsApplication=true)]

namespace Take_Note
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int appName = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int create = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int note = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int remove = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int search = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int splash = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int update = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public const int _buttonCreate = 2131099654;
			
			// aapt resource value: 0x7f06000c
			public const int _buttonDelete = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int _buttonSave = 2131099659;
			
			// aapt resource value: 0x7f060007
			public const int _buttonSearch = 2131099655;
			
			// aapt resource value: 0x7f06000d
			public const int _editTextBody = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int _editTextSearch = 2131099662;
			
			// aapt resource value: 0x7f060009
			public const int _editTextTitle = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int _imageAppName = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int _imageNote = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int _listViewNoteList = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int _textViewBody = 2131099652;
			
			// aapt resource value: 0x7f06000a
			public const int _textViewDate1 = 2131099658;
			
			// aapt resource value: 0x7f060003
			public const int _textViewDate2 = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int _textViewID = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int _textViewTitle = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomRow = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Note = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int viewSearch = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int bodyHint = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int searchHint = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int titleHint = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
